theme: jekyll-theme-minimal
title: きみとぼくとめもと
description: この可愛いカメレオンがGeekoくんです
logo: ./img/c3764192d3079398321efb22ccb65c35.jpg
markdown: kramdown
plugins:
  - jekyll-org
google_analytics: UA-21221719-3

