theme: minima
title: きみとぼくとめもと
author: kimitoboku
email: kimitoboku@techack.net
description: なんか適当にメモとかまとめる予定です。自分用なので適当です。
logo: ./img/c3764192d3079398321efb22ccb65c35.jpg

markdown: kramdown
plugins:
  - jekyll-org
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
google_analytics: UA-21221719-3

minima:
  social_links:
    twitter: Kawakami_Kento
    github: kimitoboku
    keybase: kimitoboku
    linkedin: kimitoboku
    mastodon:
      - username: kimitoboku
        instance: fla.red

header_pages:
  - about.md
