theme: jekyll-theme-hacker
title: きみとぼくとめもと
description: なんか適当にメモとかまとめる予定です。自分用なので適当です。
logo: ./img/c3764192d3079398321efb22ccb65c35.jpg
markdown: kramdown
plugins:
  - jekyll-org
  - jekyll-sitemap
google_analytics: UA-21221719-3

social_links:
  twitter: Kawakami_Kento
  github: kimitoboku
  keybase: kimitoboku
  linkedin: kimitoboku
  mastodon:
    - username: kimitoboku
      instance: fla.red

